### ISSUE TITLE
多张图片呢？我复制你上面的两个地址，放在后面显示不出来

### ISSUE THREAD

**Issue by anjiao** [babylikebird/htmlImage#1]
如题

**Comment by yangxiufeng666** [comment]
多谢关注，这个问题的原因是：UIL加载同一URL图片造成的，通过LOG：ImageAware is reused for another image. Task is cancelled.可以看出。你可以参考一下http://www.cnblogs.com/angeldevil/p/4351203.html。这个问题，我会抽时间来解决。

**Comment by yangxiufeng666** [comment]
已修复
